name: ticket_prod_v2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.1.8+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  auto_route: ^9.2.2
  bloc: ^8.1.4
  camera: ^0.11.0+2
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  google_mlkit_barcode_scanning: ^0.12.0
  google_mlkit_text_recognition: ^0.13.0
  intl: ^0.18.1
  json_annotation: ^4.9.0
  talker_dio_logger: ^4.4.1
  talker_flutter: ^4.4.1
  package_info_plus: ^8.0.2
  shared_preferences: ^2.3.2

  

# Dependency Overrides:
dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  auto_route_generator: ^9.0.0
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  


flutter:


  uses-material-design: true
  # generate: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/ml/

flutter_launcher_icons:
  android: "launcher_icons"
  ios: true
  image_path: "assets/icons/logo_app_tessera_dark.png"


# flutter_intl:
  # enabled: true

