name: ticket_prod_v2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.0.5+2

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  dio: ^5.3.3
  shared_preferences: ^2.2.1
  auto_route: ^7.8.3
  get_it: ^7.6.4
  firebase_performance_dio: ^0.6.0
  curl_logger_dio_interceptor: ^1.0.0
  camera: ^0.10.5+5
  provider: ^6.1.1
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  google_mlkit_barcode_scanning: ^0.10.0
  google_mlkit_text_recognition: ^0.11.0
  intl: ^0.18.1
  talker_flutter: ^3.5.7
  talker_dio_logger: ^2.3.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.0
  flutter_lints: ^2.0.0
  mocktail: ^1.0.1
  flutter_launcher_icons: ^0.13.1
  


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/ml/
    - i18n/kk.json
    - i18n/ru.json
    - i18n/en.json
    - i18n/uk.json
    - i18n/privacy.json

flutter_launcher_icons:
  android: "launcher_icons"
  ios: true
  image_path: "assets/icons/ic_launcher.png"

